zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    management:
      url: ${MANAGEMENT_URL:http://localhost:4200}
    api:
      url: ${API_URL:http://localhost:9999}
